#!/usr/bin/env python3

import re
import os
import subprocess
from collections import defaultdict

# Patterns to extract
pattern = re.compile(
    r"call\s+Gpu\s*%\s*(Vector|Matrix)_(Real|Int)_(Copy_To_Device|Create_On_Device)\s*\(\s*([\w\s%()]+)\s*\)",
    re.IGNORECASE
)

# Final mapping: pointer_name → type
pointers = defaultdict(str)

# Files to search
cmd = "find . ../../Shared -name '*Copy*.f??'"
if os.path.isdir("../Shared"):
  cmd = "find . ../Shared -name '*Copy*.f??'"

files = subprocess.check_output(cmd, shell=True).decode().splitlines()

for file in files:
  with open(file.strip(), 'r') as f:
    for line in f:
      match = pattern.search(line)
      if match:
        vector_type = match.group(2).lower()     # real or int
        full_expr   = match.group(4)             # e.g., Flow % pp % n

        # Special case: skip scalar(sc) → handled separately
        if 'scalar(' in full_expr.lower():
          continue

        # Turn e.g. Flow % pp % n → flow_pp_n
        pointer_name = full_expr.replace('%', '_').replace('(', '_').replace(')', '').replace(' ', '').lower()

        # Store if not already seen
        if pointer_name not in pointers:
          pointers[pointer_name] = vector_type

# Now generate Gpu_Pointers_Mod.f90
with open("Gpu_Pointers_Mod.aut", "w") as f:
  f.write('!===============================================================================!\n')
  f.write('!   DO NOT EDIT THIS FILE! THIS FILE IS GENERATED BY generate_gpu_pointers.py   !\n')
  f.write('!===============================================================================!\n\n')
  f.write('module Gpu_Pointers_Mod\n')
  f.write('  implicit none\n\n')

  for pointer, kind in sorted(pointers.items()):
    if kind == 'real':
      f.write(f'  real,    contiguous, pointer :: {pointer}(:)\n')
    else:
      f.write(f'  integer, contiguous, pointer :: {pointer}(:)\n')

  f.write('\nend module\n')

print(f"Generated Gpu_Pointers_Mod.aut with {len(pointers)} pointers.")

