rm -f */*/*.cns
rm -f */*/*.geo
rm -f */*/*.backup
rm -f */*/*vtu
rm -f */*/*cgns
rm -f */*/*.buf
rm -f */*/*.map
rm -f */*/*-monit*
rm -f */*/Generate
rm -f */*/Convert
rm -f */*/Divide
rm -f */*/Process

rm -f */*/*/*.cns
rm -f */*/*/*.geo
rm -f */*/*/*.backup
rm -f */*/*/*vtu
rm -f */*/*/*cgns
rm -f */*/*/*.buf
rm -f */*/*/*.map
rm -f */*/*/*-monit*
rm -f */*/*/Generate
rm -f */*/*/Convert
rm -f */*/*/Divide
rm -f */*/*/Process

rm -f */*/*/*/*.cns
rm -f */*/*/*/*.geo
rm -f */*/*/*/*.backup
rm -f */*/*/*/*vtu
rm -f */*/*/*/*cgns
rm -f */*/*/*/*.buf
rm -f */*/*/*/*.map
rm -f */*/*/*/*-monit*
rm -f */*/*/*/Generate
rm -f */*/*/*/Convert
rm -f */*/*/*/Divide
rm -f */*/*/*/Process

rm -f */*/*/*/*/*.cns
rm -f */*/*/*/*/*.geo
rm -f */*/*/*/*/*.backup
rm -f */*/*/*/*/*vtu
rm -f */*/*/*/*/*cgns
rm -f */*/*/*/*/*.buf
rm -f */*/*/*/*/*.map
rm -f */*/*/*/*/*-monit*
rm -f */*/*/*/*/Generate
rm -f */*/*/*/*/Convert
rm -f */*/*/*/*/Divide
rm -f */*/*/*/*/Process
