!==============================================================================!
  subroutine Create_Dodecahedron(Pol)
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  class(Polyhedron_Type) :: Pol
!-----------------------------------[Locals]-----------------------------------!
  integer :: i, is
  real    :: a, b, c
!==============================================================================!

  a = 1.0/(3.0)**0.5
  b = ((3.0-(5.0)**0.5)/6.0)**0.5
  c = ((3.0+(5.0)**0.5)/6.0)**0.5

  Pol % n_faces = 12
  Pol % n_nodes = 20

  i = 1
  Pol % nodes_xyz(i,1) = a
  Pol % nodes_xyz(i,2) = a
  Pol % nodes_xyz(i,3) = a
  i = i+1
  Pol % nodes_xyz(i,1) = a
  Pol % nodes_xyz(i,2) = a
  Pol % nodes_xyz(i,3) = -a
  i = i+1
  Pol % nodes_xyz(i,1) = a
  Pol % nodes_xyz(i,2) = -a
  Pol % nodes_xyz(i,3) = a
  i = i+1
  Pol % nodes_xyz(i,1) = a
  Pol % nodes_xyz(i,2) = -a
  Pol % nodes_xyz(i,3) = -a
  i = i+1
  Pol % nodes_xyz(i,1) = -a
  Pol % nodes_xyz(i,2) = a
  Pol % nodes_xyz(i,3) = a
  i = i+1
  Pol % nodes_xyz(i,1) = -a
  Pol % nodes_xyz(i,2) = a
  Pol % nodes_xyz(i,3) = -a
  i = i+1
  Pol % nodes_xyz(i,1) = -a
  Pol % nodes_xyz(i,2) = -a
  Pol % nodes_xyz(i,3) = a
  i = i+1
  Pol % nodes_xyz(i,1) = -a
  Pol % nodes_xyz(i,2) = -a
  Pol % nodes_xyz(i,3) = -a
  i = i+1
  Pol % nodes_xyz(i,1) = b
  Pol % nodes_xyz(i,2) = c
  Pol % nodes_xyz(i,3) = 0.0
  i = i+1
  Pol % nodes_xyz(i,1) = -b
  Pol % nodes_xyz(i,2) = c
  Pol % nodes_xyz(i,3) = 0.0
  i = i+1
  Pol % nodes_xyz(i,1) = b
  Pol % nodes_xyz(i,2) = -c
  Pol % nodes_xyz(i,3) = 0.0
  i = i+1
  Pol % nodes_xyz(i,1) = -b
  Pol % nodes_xyz(i,2) = -c
  Pol % nodes_xyz(i,3) = 0.0
  i = i+1
  Pol % nodes_xyz(i,1) = c
  Pol % nodes_xyz(i,2) = 0.0
  Pol % nodes_xyz(i,3) = b
  i = i+1
  Pol % nodes_xyz(i,1) = c
  Pol % nodes_xyz(i,2) = 0.0
  Pol % nodes_xyz(i,3) = -b
  i = i+1
  Pol % nodes_xyz(i,1) = -c
  Pol % nodes_xyz(i,2) = 0.0
  Pol % nodes_xyz(i,3) = b
  i = i+1
  Pol % nodes_xyz(i,1) = -c
  Pol % nodes_xyz(i,2) = 0.0
  Pol % nodes_xyz(i,3) = -b
  i = i+1
  Pol % nodes_xyz(i,1) = 0.0
  Pol % nodes_xyz(i,2) = b
  Pol % nodes_xyz(i,3) = c
  i = i+1
  Pol % nodes_xyz(i,1) = 0.0
  Pol % nodes_xyz(i,2) = -b
  Pol % nodes_xyz(i,3) = c
  i = i+1
  Pol % nodes_xyz(i,1) = 0.0
  Pol % nodes_xyz(i,2) = b
  Pol % nodes_xyz(i,3) = -c
  i = i+1
  Pol % nodes_xyz(i,1) = 0.0
  Pol % nodes_xyz(i,2) = -b
  Pol % nodes_xyz(i,3) = -c
  do is = 1,Pol % n_faces
    Pol % faces_n_nodes(is) = 5
  end do
  is = 1
  i = 1
  Pol % faces_n(is,i) = 1
  i = i+1
  Pol % faces_n(is,i) = 9
  i = i+1
  Pol % faces_n(is,i) = 10
  i = i+1
  Pol % faces_n(is,i) = 5
  i = i+1
  Pol % faces_n(is,i) = 17
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 1
  i = i+1
  Pol % faces_n(is,i) = 17
  i = i+1
  Pol % faces_n(is,i) = 18
  i = i+1
  Pol % faces_n(is,i) = 3
  i = i+1
  Pol % faces_n(is,i) = 13
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 13
  i = i+1
  Pol % faces_n(is,i) = 3
  i = i+1
  Pol % faces_n(is,i) = 11
  i = i+1
  Pol % faces_n(is,i) = 4
  i = i+1
  Pol % faces_n(is,i) = 14
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 10
  i = i+1
  Pol % faces_n(is,i) = 6
  i = i+1
  Pol % faces_n(is,i) = 16
  i = i+1
  Pol % faces_n(is,i) = 15
  i = i+1
  Pol % faces_n(is,i) = 5
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 4
  i = i+1
  Pol % faces_n(is,i) = 20
  i = i+1
  Pol % faces_n(is,i) = 19
  i = i+1
  Pol % faces_n(is,i) = 2
  i = i+1
  Pol % faces_n(is,i) = 14
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 8
  i = i+1
  Pol % faces_n(is,i) = 12
  i = i+1
  Pol % faces_n(is,i) = 7
  i = i+1
  Pol % faces_n(is,i) = 15
  i = i+1
  Pol % faces_n(is,i) = 16
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 1
  i = i+1
  Pol % faces_n(is,i) = 13
  i = i+1
  Pol % faces_n(is,i) = 14
  i = i+1
  Pol % faces_n(is,i) = 2
  i = i+1
  Pol % faces_n(is,i) = 9
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 9
  i = i+1
  Pol % faces_n(is,i) = 2
  i = i+1
  Pol % faces_n(is,i) = 19
  i = i+1
  Pol % faces_n(is,i) = 6
  i = i+1
  Pol % faces_n(is,i) = 10
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 17
  i = i+1
  Pol % faces_n(is,i) = 5
  i = i+1
  Pol % faces_n(is,i) = 15
  i = i+1
  Pol % faces_n(is,i) = 7
  i = i+1
  Pol % faces_n(is,i) = 18
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 7
  i = i+1
  Pol % faces_n(is,i) = 12
  i = i+1
  Pol % faces_n(is,i) = 11
  i = i+1
  Pol % faces_n(is,i) = 3
  i = i+1
  Pol % faces_n(is,i) = 18
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 8
  i = i+1
  Pol % faces_n(is,i) = 16
  i = i+1
  Pol % faces_n(is,i) = 6
  i = i+1
  Pol % faces_n(is,i) = 19
  i = i+1
  Pol % faces_n(is,i) = 20
  is = is+1
  i = 1
  Pol % faces_n(is,i) = 8
  i = i+1
  Pol % faces_n(is,i) = 20
  i = i+1
  Pol % faces_n(is,i) = 4
  i = i+1
  Pol % faces_n(is,i) = 11
  i = i+1
  Pol % faces_n(is,i) = 12

  end subroutine
