!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine User_Mod_Source(Grid, Flow, Turb, phi, sc, a, b)
!------------------------------------------------------------------------------!
!   This is a prototype of a function for customized source for scalar.        !
!   It is called from "Compute_Scalar" function, just before calling the       !
!   linear solver.  Both system matrix ("a_matrix") and right hand side        !
!   vector ("b_vector") are sent should the user want to stabilize the         !
!   system for always positive variables, for example.                         !
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  type(Grid_Type)          :: Grid
  type(Field_Type), target :: Flow
  type(Turb_Type)          :: Turb
  type(Var_Type),   target :: phi
  integer                  :: sc
  type(Sparse_Type)        :: a
  real, dimension(:)       :: b
!----------------------------------[Locals]------------------------------------!
  real    :: heat, area_x
  integer :: c, c2, reg, s
!==============================================================================!

  if( phi % name .eq. 'T' ) then

    !---------------------------------------------------------!
    !   If there is no bulk velocity (yet), get out of here   !
    !---------------------------------------------------------!
    if(abs(Flow % bulk % u) .lt. NANO) return

    !-------------------------------------!
    !   Compute heat flux to the domain   !
    !-------------------------------------!
    heat = 0.0
    do reg = Boundary_Regions()
      if(Grid % region % type(reg) .eq. WALLFL) then

        !$acc parallel loop reduction(+: heat)  &
        !$acc present(  &
        !$acc   grid_region_f_face,  &
        !$acc   grid_region_l_face,  &
        !$acc   grid_faces_c,  &
        !$acc   grid_sz,  &
        !$acc   flow_t_q   &
        !$acc )
        do s = grid_region_f_face(reg), grid_region_l_face(reg)  ! all present
          c2 = grid_faces_c(2,s)
          heat = heat + abs(grid_sz(s)) * flow_t_q(c2)
        end do
        !$acc end parallel

      end if
    end do

    !----------------------------------------!
    !   Cross-sectional area is hard-coded   !
    !----------------------------------------!
    area_x = 2.0 * 3.14

    !-------------------------------!
    !  Set source for temperature   !
    !-------------------------------!
    !$acc parallel loop independent  &
    !$acc present(  &
    !$acc   grid_region_f_cell,  &
    !$acc   grid_region_l_cell,  &
    !$acc   b,  &
    !$acc   flow_u_n,  &
    !$acc   grid_vol   &
    !$acc )
    do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions)
      b(c) = b(c) - flow_u_n(c) / Flow % bulk % u   &
                  * heat / area_x                       &
                  * grid_vol(c) / Grid % per_x
    end do
    !$acc end parallel

  end if

  end subroutine
