!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine User_Mod_Source(Grid, Flow, Turb, phi, sc)
!------------------------------------------------------------------------------!
!   User-defined source terms for scalar variables.                            !
!   Be mindful that this can be performed on the GPUs                          !
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  type(Grid_Type),     target   :: Grid
  type(Field_Type),    target   :: Flow
  type(Turb_Type),     target   :: Turb
  type(Var_Type),      target   :: phi   !! scalar being solved
  integer, intent(in), optional :: sc    !! scalar rank (optional)
!-----------------------------------[Locals]-----------------------------------!
  real,      contiguous, pointer :: val(:)  ! pointer to matrix values
  integer,   contiguous, pointer :: dia(:)  ! pointer to matrix diagonal
  real,      contiguous, pointer :: b(:)    ! pointer to right hand side
  integer                        :: c       ! cell counter
!==============================================================================!

  !-----------------------------!
  !   First take some aliases   !
  !-----------------------------!
  val => Flow % Nat % A % val
  dia => Flow % Nat % A % dia
  b   => Flow % Nat % b

  !------------------------------------!
  !                                    !
  !   Insert some source for scalars   !
  !                                    !
  !------------------------------------!
  if(present(sc)) then

    !-----------------------!
    !   Focus on scalar 1   !
    !-----------------------!
    if(sc .eq. 1) then
      !$acc parallel loop independent  &
      !$acc present(  &
      !$acc   grid_region_f_cell,  &
      !$acc   grid_region_l_cell,  &
      !$acc   b,  &
      !$acc   grid_vol   &
      !$acc )
      do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions)
        b(c) = b(c) + 0.0 * grid_vol(c)
      end do
      !$acc end parallel
    end if

  end if

  end subroutine
