from Finder.clean_whitespaces import clean_whitespaces
from Finder.get_all_var       import get_all_var
from Finder.get_call          import get_call
from Finder.get_fun           import get_fun
from Finder.get_fun_type      import get_fun_type
from Finder.get_meth          import get_meth
from Finder.get_mod           import get_mod
from Finder.get_new_calls     import get_new_calls
from Finder.get_only_meth     import get_only_meth
from Finder.get_prog          import get_prog
from Finder.get_sub           import get_sub
from Finder.get_type          import get_type
from Finder.get_use           import get_use
from Finder.get_var           import get_var
