!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Insert_Variable_Bc(Turb, Grid, Flow, phi, vis_eff)
!------------------------------------------------------------------------------!
  implicit none
!------------------------------------------------------------------------------!
  class(Turb_Type)         :: Turb
  type(Grid_Type),  target :: Grid
  type(Field_Type), target :: Flow
  type(Var_Type),   target :: phi
  real                     :: vis_eff(-Grid % n_bnd_cells:Grid % n_cells)
!-----------------------------------[Locals]-----------------------------------!
  real, contiguous, pointer :: b(:), fc(:)
  real                      :: a12
  integer                   :: reg, s, c, c1, c2
!==============================================================================!

  call Profiler % Start('Insert_Variable_Bc')

  ! Take some aliases
  b    => Flow % Nat % b
  fc   => Flow % Nat % C % fc

  !-----------------------------------------------------------------------!
  !   Handle boundary conditions on the right-hand side (in the source)   !
  !-----------------------------------------------------------------------!

  !$acc parallel loop independent  &
  !$acc present(  &
  !$acc   grid_region_f_cell,  &
  !$acc   grid_region_l_cell,  &
  !$acc   b   &
  !$acc )
  do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions+1)  ! all present
    b(c) = 0.0
  end do
  !$acc end parallel

  if(phi % name .eq. 'VIS') then
    do reg = Boundary_Regions()
      if(Grid % region % type(reg) .eq. WALL .or.  &
         Grid % region % type(reg) .eq. INFLOW) then
  
        phi_n => phi % n
        !$acc parallel loop  &
        !$acc present(  &
        !$acc   grid_region_f_face,  &
        !$acc   grid_region_l_face,  &
        !$acc   grid_faces_c,  &
        !$acc   vis_eff,  &
        !$acc   fc,  &
        !$acc   b,  &
        !$acc   phi_n   &
        !$acc )
        do s = grid_region_f_face(reg), grid_region_l_face(reg)  ! all present
          c1 = grid_faces_c(1,s)
          c2 = grid_faces_c(2,s)
          a12 = vis_eff(c1) * fc(s)
          b(c1) = b(c1) + a12 * phi_n(c2)
        end do
        !$acc end parallel
  
      end if
    end do
  end if

  call Profiler % Stop('Insert_Variable_Bc')

  end subroutine
