!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Vis_T_Spalart_Allmaras(Turb, Grid, Flow)
!------------------------------------------------------------------------------!
!   Computes the turbulent viscosity for RANS models.                          !
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  class(Turb_Type), target :: Turb
  type(Grid_Type)          :: Grid
  type(Field_Type)         :: Flow
!-----------------------------------[Locals]-----------------------------------!
  type(Var_Type),   pointer :: u, v, w
  type(Var_Type),   pointer :: vis
  integer                   :: c, s, c1, c2
  real                      :: x_rat, f_v1
  real                      :: nx, ny, nz
  real                      :: cs, lf, u_tau, nc2, u_tan, nu
  real                      :: beta, pr, ebf, u_plus, pr_t, sc, z_o, kin_vis
!------------------------------[Local parameters]------------------------------!
  real, parameter           :: A_POW = 8.3
  real, parameter           :: B_POW = 1.0/7.0
!==============================================================================!

  ! Take aliases
  vis  => Turb % vis
  call Flow % Alias_Momentum(u, v, w)

  if(Turb % model .eq. DES_SPALART) then
    do c = Cells_In_Domain_And_Buffers()
      x_rat    = vis % n(c) / (Flow % viscosity(c)/Flow % density(c))
      f_v1     = x_rat**3/(x_rat**3 + Turb % c_v1**3)
      Turb % vis_t(c) = Flow % density(c) * f_v1 * vis % n(c)
    end do
  end if

  if(Turb % model .eq. SPALART_ALLMARAS) then
    do c = Cells_In_Domain_And_Buffers()
      x_rat = vis % n(c) / (Flow % viscosity(c)/Flow % density(c))
      f_v1  = x_rat**3/(x_rat**3 + Turb % c_v1**3)
      Turb % vis_t(c) = Flow % density(c) * f_v1 * vis % n(c)
    end do
  end if


  !-------------------!
  !   Wall function   !
  !-------------------+--------------!
  !   Law of the wall:               !
  !                                  !
  !   u+ = yz+  for z+ < 11.81       !
  !                                  !
  !   and                            !
  !                                  !
  !   u+ = A(y+)^B   for y+ > 11.81  !
  !                                  !
  !   with: A = 8.3 and B = 1/7      !
  !                                  !
  !----------------------------------+----------!
  !   The procedure below should be activated   !
  !   only if wall function approach is used.   !
  !----------------.----------------------------!
  do s = 1, Grid % n_faces
    c1 = Grid % faces_c(1,s)
    c2 = Grid % faces_c(2,s)

    if(c2  < 0) then

      nx = Grid % sx(s) / Grid % s(s)
      ny = Grid % sy(s) / Grid % s(s)
      nz = Grid % sz(s) / Grid % s(s)

      if(Grid % Bnd_Cond_Type(c2) .eq. WALL .or.  &
         Grid % Bnd_Cond_Type(c2) .eq. WALLFL) then

        kin_vis =  Flow % viscosity(c1) / Flow % density(c1)

        ! Set up roughness coefficient
        z_o = Turb % Roughness_Coeff(Grid, c1, c2)

        u_tan = Flow % U_Tan(Grid, s)

        nu = Flow % viscosity(c1) / Flow % density(c1)
                ! Calculate u_tau for smooth wall
        u_tau = (u_tan/A_POW * (nu/Grid % wall_dist(c1))**B_POW) &
                ** (1.0/(1.0+B_POW))

        ! Calculate u_tau for rough wall
        if(z_o .gt. TINY) then
          u_tau = u_tan * Turb % kappa / log(Grid % wall_dist(c1)/z_o)
        end if

        ! Calculate y+
        Turb % y_plus(c1) = Turb % Y_Plus_Rough_Walls(    &
                                   u_tau,                 &
                                   Grid % wall_dist(c1),  &
                                   kin_vis,               &
                                   z_o)

        u_plus = Turb % U_Plus_Log_Law(               &
                               Grid % wall_dist(c1),  &
                               Turb % y_plus(c1),     &
                               z_o)


        ebf = Turb % Ebf_Momentum(c1)

        if(Turb % y_plus(c1) < 3.0) then
          Turb % vis_w(c1) = Turb % vis_t(c1) + Flow % viscosity(c1)
        else

          if(Turb % y_plus(c1) < 11.3 ) then
            ebf = 0.00001
          end if

          Turb % vis_w(c1) =    Turb % y_plus(c1) * Flow % viscosity(c1)  &
                           / (  Turb % y_plus(c1) * exp(-1.0 * ebf)       &
                              + u_plus * exp(-1.0/ebf) + TINY)

        end if

        if(Flow % heat_transfer) then
          pr_t = Turb % Prandtl_Turb(Flow, c1)
          pr   = Flow % Prandtl_Numb(c1)          ! laminar Prandtl number
          beta = Turb % Beta_Scalar(pr, pr_t)
          ! According to Toparlar et al. 2019 paper
          ! "CFD simulation of the near-neutral atmospheric boundary layer: New
          ! temperature inlet profile consistent with wall functions"
          if(z_o .gt. TINY) then
            beta = 0.0
          end if

          ebf = Turb % Ebf_Scalar(c1, pr)
          Turb % con_w(c1) =    Turb % y_plus(c1)                         &
                              * Flow % viscosity(c1)                      &
                              * Flow % capacity(c1)                       &
                      / (  Turb % y_plus(c1) * pr * exp(-1.0 * ebf)       &
                         + (u_plus + beta) * pr_t * exp(-1.0 / ebf) + TINY)
        end if

        if(Flow % n_scalars > 0) then
          sc   = Flow % Schmidt_Numb(c1)          ! laminar Schmidt number
          beta = Turb % Beta_Scalar(sc, sc_t)
          ! According to Toparlar et al. 2019 paper
          ! "CFD simulation of the near-neutral atmospheric boundary layer: New
          ! temperature inlet profile consistent with wall functions"
          if(z_o .gt. TINY) then
            beta = 0.0
          end if

          ebf = Turb % Ebf_Scalar(c1, sc)
          Turb % diff_w(c1) =  Turb % y_plus(c1)                  &
              * (Flow % viscosity(c1)/Flow % density(c1))         &
              / (Turb % y_plus(c1) * sc * exp(-1.0 * ebf)         &
               + (u_plus + beta) * sc_t * exp(-1.0 / ebf) + TINY)

        end if

      end if  ! Grid % Bnd_Cond_Type(c2) .eq. WALL or WALLFL
    end if    ! c2 < 0
  end do

  call Grid % Exchange_Cells_Real(Turb % vis_w)
  if(Flow % n_scalars > 0) call Grid % Exchange_Cells_Real(Turb % diff_w)
  if(Flow % heat_transfer) call Grid % Exchange_Cells_Real(Turb % con_w)

  call Grid % Exchange_Cells_Real(Turb % vis_t)

  end subroutine
