!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Wall_Function(Turb, Grid, Flow)
!------------------------------------------------------------------------------!
!   Computes turbulent viscosity for near-wall regions with wall functions     !
!------------------------------------------------------------------------------!
  implicit none
!---------------------------------[Arguments]----------------------------------!
  class(Turb_Type), target :: Turb
  type(Grid_Type)          :: Grid
  type(Field_Type)         :: Flow
!-----------------------------------[Locals]-----------------------------------!
  integer :: reg, s, c1, c2
  real    :: u_tau, u_tan, nu
  real    :: beta, pr, ebf, u_plus, pr_t, sc, z_o, kin_vis
!------------------------------[Local parameters]------------------------------!
  real, parameter :: A_POW = 8.3
  real, parameter :: B_POW = 1.0/7.0
!==============================================================================!

  !-------------------!
  !                   !
  !   Wall function   !
  !                   !
  !-------------------+--------------!
  !   Law of the wall:               !
  !                                  !
  !   u+ = yz+  for z+ < 11.81       !
  !                                  !
  !   and                            !
  !                                  !
  !   u+ = A(y+)^B   for y+ > 11.81  !
  !                                  !
  !   with: A = 8.3 and B = 1/7      !
  !                                  !
  !----------------------------------+----------!
  !   The procedure below should be activated   !
  !   only if wall function approach is used.   !
  !---------------------------------------------!
  do reg = Boundary_Regions()

    if(Grid % region % type(reg) .eq. WALL    .or.  &
       Grid % region % type(reg) .eq. WALLFL) then

      !$acc parallel loop  &
      !$acc present(  &
      !$acc   grid_region_f_face,  &
      !$acc   grid_region_l_face,  &
      !$acc   grid_faces_c,  &
      !$acc   flow_viscosity,  &
      !$acc   flow_density,  &
      !$acc   turb_z_o,  &
      !$acc   grid_wall_dist,  &
      !$acc   turb_y_plus,  &
      !$acc   flow_u_n,  &
      !$acc   flow_v_n,  &
      !$acc   flow_w_n,  &
      !$acc   turb_vis_w,  &
      !$acc   turb_vis_t,  &
      !$acc   flow_capacity,  &
      !$acc   flow_conductivity,  &
      !$acc   turb_con_w,  &
      !$acc   flow_diffusivity,  &
      !$acc   turb_diff_w   &
      !$acc )
      do s = grid_region_f_face(reg), grid_region_l_face(reg)  ! all present
        c1 = grid_faces_c(1,s)
        c2 = grid_faces_c(2,s)

        kin_vis =  flow_viscosity(c1) / flow_density(c1)

        !----------------------------------!
        !   Set up roughness coefficient   !
        !----------------------------------!
        z_o = turb_z_o(c2)    ! take the value specified in control file
        if(z_o .gt. TINY) then  ! set lower limit based on wall distance
          z_o = max(grid_wall_dist(c1)  &
              / (Turb % e_log * max(turb_y_plus(c1), 1.0)), z_o)
        end if

        !------------------------------------------------!
        !   Work out the tangential velocity component   !
        !   (Assume it is the same ase the magnitude)    !
        !------------------------------------------------!
        u_tan = sqrt(  flow_u_n(c1) ** 2   &
                     + flow_v_n(c1) ** 2   &
                     + flow_w_n(c1) ** 2)

        nu = flow_viscosity(c1) / flow_density(c1)

        !---------------------!
        !   Calculate u_tau   !
        !---------------------!

        ! First calculate u_tau for smooth wall ...
        u_tau = (u_tan/A_POW * (nu/grid_wall_dist(c1))**B_POW) &
                ** (1.0/(1.0+B_POW))

        ! ... then correct, if needed, for rough wall
        if(z_o .gt. TINY) then
          u_tau = u_tan * Turb % kappa / log(grid_wall_dist(c1)/z_o)
        end if

!1 !future ! Calculate u_tau according to Monin-Obukov Similarity Theory
!1 !future if(Flow % heat_transfer .and. Turb % monin_obukov) then
!1 !future   u_tau = u_tau * Turb % Monin_Obukov_Momentum(abs(u_tan),  &
!1 !future           grid_wall_dist(c1), z_o, t % n(c1),             &
!1 !future           t % n(c2), abs(Flow % grav_z))
!1 !future end if

        !------------------!
        !   Calculate y+   !
        !------------------!
        turb_y_plus(c1) = u_tau * (grid_wall_dist(c1) + z_o) / kin_vis

        !------------------!
        !   Calculate u+   !
        !------------------!

        ! First salculate u+ for smooth walls ...
        u_plus = log( max(turb_y_plus(c1), 1.05) * Turb % e_log )  &
               / Turb % kappa

        ! ... then correct, if needed, for rough walls
        if(z_o > TINY) then
          u_plus = log( (grid_wall_dist(c1) + z_o) / z_o)  &
                 / (Turb % kappa + TINY) + TINY
        end if

        !-------------------------------------------------!
        !   Calculate blending coefficient for momentum   !
        !-------------------------------------------------!
        ebf = max(   0.01 * turb_y_plus(c1)**4            &
                  / (1.0 + 5.0 * turb_y_plus(c1)), TINY)

        if(turb_y_plus(c1) < 3.0) then
          turb_vis_w(c1) = turb_vis_t(c1) + flow_viscosity(c1)
        else
          turb_vis_w(c1) =    turb_y_plus(c1) * flow_viscosity(c1)  &
                           / (  turb_y_plus(c1) * exp(-1.0 * ebf)       &
                              + u_plus * exp(-1.0/ebf) + TINY)
        end if

        !-------------------------------------------------!
        !   For heat transfer problems, calculate con_w   !
        !-------------------------------------------------!
        if(Flow % heat_transfer) then
          pr_t = 0.4                      ! WARNING: GOOD ONLY FOR LES
          pr   = flow_viscosity(c1)  &  ! laminar Prandtl number
               * flow_capacity(c1)   &
               / flow_conductivity(c1)
          beta = 9.24 * ((pr/pr_t)**0.75 - 1.0)  &
                      * (1.0 + 0.28 * exp(-0.007*pr/pr_t))
          ! According to Toparlar et al. 2019 paper
          ! "CFD simulation of the near-neutral atmospheric boundary layer: New
          ! temperature inlet profile consistent with wall functions"
          if(z_o .gt. TINY) then
            beta = 0.0
          end if

          ! Calculate blending coefficient for scalar(s)
          ebf = 0.01 * ((pr * turb_y_plus(c1)) ** 4  &
              / ((1.0 + 5.0 * pr**3 * turb_y_plus(c1)) + TINY))

          turb_con_w(c1) =    turb_y_plus(c1)                         &
                              * flow_viscosity(c1)                      &
                              * flow_capacity(c1)                       &
                      / (  turb_y_plus(c1) * pr * exp(-1.0 * ebf)       &
                         + (u_plus + beta) * pr_t * exp(-1.0 / ebf) + TINY)

!1 !future   if(Turb % monin_obukov) then
!1 !future     turb_con_w(c1) = pr_t * turb_con_w(c1)                  &
!1 !future                      * Turb % Monin_Obukov_Thermal(abs(u_tan),  &
!1 !future                        grid_wall_dist(c1), z_o, t % n(c1),    &
!1 !future                        t % n(c2),                               &
!1 !future                        abs(Flow % grav_z))
!1 !future   end if
        end if  ! heat transfer

        !-----------------------------------------------------!
        !   For scalar transport problems, calculate diff_w   !
        !-----------------------------------------------------!
        if(Flow % n_scalars > 0) then
          sc =  flow_viscosity(c1)  &                       ! Schmidt number
             / (flow_diffusivity(c1) * flow_density(c1))
          beta = 9.24 * ((sc/sc_t)**0.75 - 1.0)  &
                      * (1.0 + 0.28 * exp(-0.007*sc/sc_t))
          ! According to Toparlar et al. 2019 paper
          ! "CFD simulation of the near-neutral atmospheric boundary layer: New
          ! temperature inlet profile consistent with wall functions"
          if(z_o .gt. TINY) then
            beta = 0.0
          end if

          ! Calculate blending coefficient for scalar(s)
          ebf = 0.01 * ((sc * turb_y_plus(c1)) ** 4  &
              / ((1.0 + 5.0 * sc**3 * turb_y_plus(c1)) + TINY))
          turb_diff_w(c1) =  turb_y_plus(c1)                  &
              * (flow_viscosity(c1)/flow_density(c1))         &
              / (turb_y_plus(c1) * sc * exp(-1.0 * ebf)         &
               + (u_plus + beta) * sc_t * exp(-1.0 / ebf) + TINY)

!1 !future   if(Turb % monin_obukov) then
!1 !future     turb_diff_w(c1) = sc_t * turb_diff_w(c1)                      &
!1 !future                    * Turb % Monin_Obukov_Thermal(abs(u_tan),          &
!1 !future                      grid_wall_dist(c1), z_o, t % n(c1), t % n(c2), &
!1 !future                      abs(Flow % grav_z))
!1 !future   end if
        end if  ! n_scalars > 0

      end do
      !$acc end parallel    ! s, faces

    end if      ! is it WALL or WALLFL?
  end do        ! through regions

  call Grid % Exchange_Cells_Real(Turb % vis_w)
  if(Flow % n_scalars > 0) call Grid % Exchange_Cells_Real(Turb % diff_w)
  if(Flow % heat_transfer) call Grid % Exchange_Cells_Real(Turb % con_w)

  end subroutine
