!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Compute_Momentum(Process, Grid, Flow, Turb, comp)
!------------------------------------------------------------------------------!
  implicit none
!------------------------------------------------------------------------------!
  class(Process_Type)      :: Process
  type(Grid_Type),  target :: Grid
  type(Field_Type), target :: Flow
  type(Turb_Type),  target :: Turb
  integer                  :: comp
!-----------------------------------[Locals]-----------------------------------!
  type(Sparse_Val_Type), pointer :: Aval
  type(Sparse_Con_Type), pointer :: Acon
  type(Var_Type),        pointer :: ui
  real,      contiguous, pointer :: ui_n(:), ui_o(:), ui_oo(:)
  real,      contiguous, pointer :: val(:)
  integer,   contiguous, pointer :: dia(:)
  real,      contiguous, pointer :: b(:), visc_eff(:)
  real                           :: urf
  integer                        :: c
!------------------------[Avoid unused parent warning]-------------------------!
  Unused(Process)
!==============================================================================!

  call Profiler % Start('Compute_Momentum')

  call Work % Connect_Real_Cell(visc_eff)

  Assert(comp .ge. 1)
  Assert(comp .le. 3)

  !------------------------------------------------------------!
  !   First take some aliases, which is quite elaborate here   !
  !------------------------------------------------------------!
  Acon => Flow % Nat % C
  if(Flow % Nat % use_one_matrix) then
    Aval => Flow % Nat % A(MATRIX_ONE)
    val  => Flow % Nat % A(MATRIX_ONE) % val
  else
    Aval => Flow % Nat % A(MATRIX_UVW)
    val  => Flow % Nat % A(MATRIX_UVW) % val
  end if
  dia => Flow % Nat % C % dia
  b   => Flow % Nat % b

  if(comp .eq. 1) then
    ui    => Flow % u
    ui_n  => Flow % u % n
    ui_o  => Flow % u % o
    ui_oo => Flow % u % oo
  else if(comp .eq. 2) then
    ui    => Flow % v
    ui_n  => Flow % v % n
    ui_o  => Flow % v % o
    ui_oo => Flow % v % oo
  else if(comp .eq. 3) then
    ui    => Flow % w
    ui_n  => Flow % w % n
    ui_o  => Flow % w % o
    ui_oo => Flow % w % oo
  end if

  ! Tolerances and under-relaxations are the same for all components
  urf = Flow % u % urf

  !---------------------------------------------------!
  !   Update old values (o) and older than old (oo)   !
  !---------------------------------------------------!
  if(Iter % Current() .eq. 1) then

    if(Flow % u % td_scheme .eq. PARABOLIC) then
      !$acc parallel loop independent  &
      !$acc present(  &
      !$acc   grid_region_f_cell,  &
      !$acc   grid_region_l_cell,  &
      !$acc   ui_oo,  &
      !$acc   ui_o   &
      !$acc )
      do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions+1)  ! all present
        ui_oo(c) = ui_o(c)
      end do
      !$acc end parallel
    end if

    !$acc parallel loop independent  &
    !$acc present(  &
    !$acc   grid_region_f_cell,  &
    !$acc   grid_region_l_cell,  &
    !$acc   ui_o,  &
    !$acc   ui_n   &
    !$acc )
    do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions+1)  ! all present
      ui_o(c) = ui_n(c)
    end do
    !$acc end parallel
  end if

  !----------------------------------------------------!
  !   Discretize the momentum conservation equations   !
  !----------------------------------------------------!

  ! Once is enough, it is the same for all components
  if(comp .eq. 1) then
    call Process % Form_Momentum_Matrix(Grid, Flow, Turb, Aval, visc_eff,  &
                                        urf, dt = Flow % dt)
  end if

  !----------------------------------------------------------!
  !   Insert proper sources (forces) to momentum equations   !
  !----------------------------------------------------------!

  ! From boundary conditions
  call Process % Insert_Momentum_Bc(Grid, Flow, comp=comp)

  ! Buoyancy forces
  call Flow % Buoyancy_Forces(Grid, comp)

  ! Inertial and advection terms
  if(comp .eq. 1) then
    call Flow % Add_Inertial_Term (Grid, Flow % u, Flow % density)
    call Flow % Add_Advection_Term(Grid, Flow % u, Flow % density)
    call Flow % Add_Cross_Diffusion_Term(Grid, Flow % u, visc_eff)
  else if(comp .eq. 2) then
    call Flow % Add_Inertial_Term (Grid, Flow % v, Flow % density)
    call Flow % Add_Advection_Term(Grid, Flow % v, Flow % density)
    call Flow % Add_Cross_Diffusion_Term(Grid, Flow % v, visc_eff)
  else if(comp .eq. 3) then
    call Flow % Add_Inertial_Term (Grid, Flow % w, Flow % density)
    call Flow % Add_Advection_Term(Grid, Flow % w, Flow % density)
    call Flow % Add_Cross_Diffusion_Term(Grid, Flow % w, visc_eff)
  end if

  ! Pressure force
  call Flow % Grad_Pressure(Grid, Flow % p)
  call Process % Add_Pressure_Term(Grid, Flow, comp=comp)

  !------------------------------!
  !   Perform under-relaxation   !
  !------------------------------!
  !$acc parallel loop independent  &
  !$acc present(  &
  !$acc   grid_region_f_cell,  &
  !$acc   grid_region_l_cell,  &
  !$acc   val,  &
  !$acc   dia,  &
  !$acc   b,  &
  !$acc   ui_n   &
  !$acc )
  do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions)  ! all present
    val(dia(c)) = val(dia(c)) / urf
    b(c) = b(c) + val(dia(c)) * (1.0 - urf) * ui_n(c)
  end do
  !$acc end parallel

  !------------------------!
  !   Call linear solver   !
  !------------------------!
  call Profiler % Start('CG_for_Momentum')
  call Flow % Nat % Cg(Acon, Aval, ui_n, b,     &
                       ui % miter, ui % niter,  &
                       ui % tol,   ui % res)
  call Profiler % Stop('CG_for_Momentum')

  call Info % Iter_Fill_At(1, comp, ui % name, ui % res, ui % niter)

  call Work % Disconnect_Real_Cell(visc_eff)

  call Profiler % Stop('Compute_Momentum')

  end subroutine
