!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Insert_Scalars_Bc(Process, Grid, Flow, sc)
!------------------------------------------------------------------------------!
  implicit none
!------------------------------------------------------------------------------!
  class(Process_Type)      :: Process
  type(Grid_Type),  target :: Grid
  type(Field_Type), target :: Flow
  integer, intent(in)      :: sc
!-----------------------------------[Locals]-----------------------------------!
  type(Var_Type),   pointer :: phi
  real, contiguous, pointer :: b(:), fc(:), diff(:)
  real                      :: a12
  integer                   :: reg, s, c, c1, c2
!------------------------[Avoid unused parent warning]-------------------------!
  Unused(Process)
!==============================================================================!

  call Profiler % Start('Insert_Scalars_Bc')

  ! Take some aliases
  b    => Flow % Nat % b
  fc   => Flow % Nat % A % fc
  diff => Flow % diffusivity
  phi  => Flow % scalar(sc)

  !-----------------------------------------------------------------------!
  !   Handle boundary conditions on the right-hand side (in the source)   !
  !-----------------------------------------------------------------------!

  !$acc parallel loop independent  &
  !$acc present(  &
  !$acc   grid_region_f_cell,  &
  !$acc   grid_region_l_cell,  &
  !$acc   b   &
  !$acc )
  do c = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions+1)  ! all present
    b(c) = 0.0
  end do
  !$acc end parallel

  phi_bnd_cond_type => phi % bnd_cond_type
  phi_n => phi % n
  !$acc parallel loop  &
  !$acc present(  &
  !$acc   grid_region_f_face,  &
  !$acc   grid_region_l_face,  &
  !$acc   grid_faces_c,  &
  !$acc   b,  &
  !$acc   phi_bnd_cond_type,  &
  !$acc   diff,  &
  !$acc   fc,  &
  !$acc   phi_n   &
  !$acc )
  do s = grid_region_f_face(1), grid_region_l_face(grid_n_bnd_regions)  ! all present
    c1 = grid_faces_c(1,s)    ! inside cell
    c2 = grid_faces_c(2,s)    ! boundary cell
    if(phi_bnd_cond_type(c2) .eq. WALL    .or.  &
       phi_bnd_cond_type(c2) .eq. INFLOW) then
      a12 = diff(c1) * fc(s)
      b(c1) = b(c1) + a12 * phi_n(c2)
    end if
  end do
  !$acc end parallel

  call Profiler % Stop('Insert_Scalars_Bc')

  end subroutine
