!==============================================================================!
!   DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM ITS FPP ORIGIN   !
!==============================================================================!

!==============================================================================!
  subroutine Add_Cross_Diffusion_Term(Flow, Grid, phi, coef)
!------------------------------------------------------------------------------!
!   Thoroughly re-vamped for the GPU_2                                         !
!------------------------------------------------------------------------------!
  implicit none
!------------------------------------------------------------------------------!
  class(Field_Type), target :: Flow
  type(Grid_Type)           :: Grid
  type(Var_Type),    target :: phi
  real                      :: coef(-Grid % n_bnd_cells:Grid % n_cells)
!-----------------------------------[Locals]-----------------------------------!
  real, contiguous, pointer :: b(:), fc(:)
  real                      :: b_tmp, coef_f, f_ex, f_im, blend
  real                      :: phix_f, phiy_f, phiz_f
  integer                   :: s, c1, c2, i_cel, reg
!==============================================================================!

  call Profiler % Start('Add_Cross_Diffusion_Term')

  ! Take some aliases
  b  => Flow % Nat % b
  fc => Flow % Nat % C % fc

  !--------------------------------------------!
  !   Compute gradient of the variable first   !
  !--------------------------------------------!
  call Flow % Grad_Variable(Grid, phi)

  !-------------------------------------------!
  !   Browse through all the interior cells   !
  !-------------------------------------------!

  !$acc parallel loop independent  &
  !$acc present(  &
  !$acc   grid_region_f_cell,  &
  !$acc   grid_region_l_cell,  &
  !$acc   b,  &
  !$acc   grid_cells_n_cells,  &
  !$acc   grid_cells_c,  &
  !$acc   grid_cells_f,  &
  !$acc   flow_phi_x,  &
  !$acc   flow_phi_y,  &
  !$acc   flow_phi_z,  &
  !$acc   coef,  &
  !$acc   grid_sx,  &
  !$acc   grid_sy,  &
  !$acc   grid_sz,  &
  !$acc   fc,  &
  !$acc   grid_dx,  &
  !$acc   grid_dy,  &
  !$acc   grid_dz   &
  !$acc )
  do c1 = grid_region_f_cell(grid_n_regions), grid_region_l_cell(grid_n_regions)  ! all present (this wasn't independent)
    b_tmp = b(c1)

  !$acc loop seq
    do i_cel = 1, grid_cells_n_cells(c1)
      c2 = grid_cells_c(i_cel, c1)
      s  = grid_cells_f(i_cel, c1)
      if(c2 .gt. 0) then

        ! Derivatives at the face
        phix_f = Face_Value(s, flow_phi_x(c1), flow_phi_x(c2))
        phiy_f = Face_Value(s, flow_phi_y(c1), flow_phi_y(c2))
        phiz_f = Face_Value(s, flow_phi_z(c1), flow_phi_z(c2))

        ! Value of the coefficient at the cel face
        coef_f = Face_Value(s, coef(c1), coef(c2))

        f_ex = coef_f * (  phix_f * grid_sx(s)   &
                         + phiy_f * grid_sy(s)   &
                         + phiz_f * grid_sz(s))
        f_im = coef_f * fc(s)              &
             * (  phix_f * grid_dx(s)    &
                + phiy_f * grid_dy(s)    &
                + phiz_f * grid_dz(s) )

        if(c1.gt.c2) then
          f_ex = -f_ex
          f_im = -f_im
        end if

        b_tmp = b_tmp + f_ex - f_im
      end if
    end do
  !$acc end loop

    b(c1) = b_tmp
  end do
  !$acc end parallel

  call Profiler % Stop('Add_Cross_Diffusion_Term')

  end subroutine
